apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: donaldsebleung-com
  name: donaldsebleung-com
  namespace: donaldsebleung-com
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: donaldsebleung-com
  targetCPUUtilizationPercentage: 50
