apiVersion: v1
kind: Service
metadata:
  labels:
    app: donaldsebleung-com
  name: donaldsebleung-com
  namespace: donaldsebleung-com
spec:
  selector:    
    app: donaldsebleung-com
  type: LoadBalancer
  ports:  
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
