apiVersion: v1
kind: Pod
metadata:
  labels:
    app: donaldsebleung-com
  name: donaldsebleung-com
  namespace: donaldsebleung-com
spec:
  containers:
  - name: donaldsebleung-com
    image: donaldsebleung/donaldsebleung-com:0.2.0
    ports:
    - containerPort: 8443

